stages:
  download_hugging_kaggle:
    cmd: python -m recruitair.data.download_raw_dataset
    deps:
    - recruitair/data/download_raw_dataset.py
    - recruitair/config.py
    outs:
    - data/raw/raw_jsons/
    - data/raw/job-skill-set.csv
    - data/raw/recruitment.csv
  preprocess_json:
    cmd: python -m recruitair.data.preprocess_json
    deps:
    - data/raw/raw_jsons/
    - recruitair/data/preprocess_json.py
    - recruitair/config.py
    outs:
    - data/interim/preprocessed_jobs.jsonl
